version: '3'

services:
  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secret123
    volumes:
      - ./orders-msvc/postgres:/var/lib/postgresql/data

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  products-msvc:
    build: ./products-msvc
    ports:
      - "3001:3001"
    volumes:
      - ./products-msvc/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-msvc:
    depends_on: [orders-db]
    build: ./orders-msvc
    ports:
      - "3002:3002"
    volumes:
      - ./orders-msvc/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgres://postgres:Secret123@orders-db:5432/orders_db
